---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: firewalld-webvm-rocky8
    image: rockylinux:8
    image_version: latest
    env:
      container: docker
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns: host
    pre_build_image: false
    privileged: true
  - name: firewalld-dbvm-rocky8
    image: rockylinux:8
    image_version: latest
    env:
      container: docker
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns: host
    pre_build_image: false
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../resources/playbooks/converge.yml
scenario:
  name: rocky8
verifier:
  # name: testinfra
  # directory: ../resources/tests/
  # lint:
  #   name: flake8
  name: ansible
