---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: firewall-db
    image: ${MOLECULE_DOCKER_IMAGE:-centos/systemd}
    image_version: latest
    command: ""
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: false
    privileged: true
  - name: firewall-web
    image: ${MOLECULE_DOCKER_IMAGE:-centos/systemd}
    image_version: latest
    command: ""
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: false
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
  playbooks:
    converge: ./converge.yml
  inventory:
    host_vars:
      firewall-db:
        firewall_for_web_vm: false
      firewall-web:
        firewall_for_web_vm: true
verifier:
  # name: testinfra
  # directory: ../resources/tests/
  # lint:
  #   name: flake8
  name: ansible
